### ISSUE TITLE
FileUriExposedException

### ISSUE THREAD

**Issue by ldemay** [coomar2841/android-multipicker-library#46]
When I use CameraImagePicker pickImage() on Android 7.0 (N) on Nexus 5x, with an app targeting/compiling SDK 24, I have
```
D/ImagePickerImpl: Temp Path for Camera capture: /storage/emulated/0/AppName/AppName Pictures/061aafec-0acd-488d-b8b0-c7d5fb8c152a.jpg
E/FileUpload: <AppNameFilesChooser.java:151> FileUriExposedException: android.os.FileUriExposedException: file:///storage/emulated/0/AppName/AppName%20Pictures/061aafec-0acd-488d-b8b0-c7d5fb8c152a.jpg exposed beyond app through ClipData.Item.getUri()
W/System.err:     at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
W/System.err:     at android.net.Uri.checkFileUriExposed(Uri.java:2346)
W/System.err:     at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
W/System.err:     at android.content.Intent.prepareToLeaveProcess(Intent.java:8909)
W/System.err:     at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:4224)
W/System.err:     at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
W/System.err:     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:4183)
W/System.err:     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:871)
W/System.err:     at com.kbeanie.multipicker.core.PickerManager.pickInternal(PickerManager.java:147)
W/System.err:     at com.kbeanie.multipicker.core.ImagePickerImpl.takePictureWithCamera(ImagePickerImpl.java:145)
W/System.err:     at com.kbeanie.multipicker.core.ImagePickerImpl.pick(ImagePickerImpl.java:118)
W/System.err:     at com.kbeanie.multipicker.api.CameraImagePicker.pickImage(CameraImagePicker.java:74)
...
```

**Comment by coomar2841** [comment]
Thanks for the report. Will look at this issue.

**Comment by coomar2841** [comment]
More Info: https://code.google.com/p/android/issues/detail?id=203555

**Comment by coomar2841** [comment]
Uploaded a beta build for testing it out..

```compile 'com.kbeanie:multipicker:1.1.2-beta@aar'

**Comment by ldemay** [comment]
@coomar2841 It seems to work pretty well, thanks!

**Comment by coomar2841** [comment]
Uploaded a beta build for testing it out..
```
compile 'com.kbeanie:multipicker:1.1.21-beta@aar'
```

Will make a final build sometime this week.

**Comment by livotov** [comment]
beta does not crash anymore on Nexus 5X/Nougat but for me the system camera always returns RESULT_CANCELLED code for some reason.

**Comment by coomar2841** [comment]
Can you post some logs for this?

**Comment by livotov** [comment]
Sure, here is the way we call it

`
cameraImagePicker = new CameraImagePicker(this); // "this" is the fragment, not activity
cameraImagePicker.setImagePickerCallback(new ImagePickerCallback()
        {
            @Override
            public void onImagesChosen(List<ChosenImage> list)
            {
                onPictureTaken(new File(list.get(0).getOriginalPath())); // here we'll process the pictrue
                imagePicker = null;
            }

            @Override
            public void onError(String s)
            {
            }
        });

        cameraImagePicker.pickImage();`


And here is the logcat:

`09-10 07:07:56.426 12757-12757/com.testapp D/ImagePickerImpl: takeVideoWithCamera: Temp Uri: /photos/8e40c115-c123-44bd-9905-96a80beb2241jpeg
09-10 07:07:56.426 12757-12757/com.testapp D/ImagePickerImpl: Temp Path for Camera capture: /data/user/0/com.testapp/files/pictures/8e40c115-c123-44bd-9905-96a80beb2241jpeg

09-10 07:08:06.068 13627-13627/? E/CAM_StateSavePic: exception while saving result to URI: Optional.of(content://com.testapp.multipicker.fileprovider/photos/8e40c115-c123-44bd-9905-96a80beb2241jpeg)
                                                     java.io.FileNotFoundException: No such file or directory
                                                         at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:144)
                                                         at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:621)
                                                         at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1000)
                                                         at android.content.ContentResolver.openOutputStream(ContentResolver.java:742)
                                                         at android.content.ContentResolver.openOutputStream(ContentResolver.java:718)
                                                         at com.android.camera.module.imageintent.state.StateSavingPicture.onEnter(StateSavingPicture.java:54)
                                                         at com.android.camera.module.imageintent.state.StateSavingPicture.onEnter(StateSavingPicture.java:20)
                                                         at com.android.camera.fsm.StateMachineImpl.jumpToState(StateMachineImpl.java:50)
                                                         at com.android.camera.fsm.StateMachineImpl.processEvent(StateMachineImpl.java:104)
                                                         at com.android.camera.module.imageintent.state.StateOpeningCamera$8.onClick(StateOpeningCamera.java:288)
                                                         at android.view.View.performClick(View.java:5609)
                                                         at com.android.camera.ui.BottomBar$1.onClick(BottomBar.java:116)
                                                         at android.view.View.performClick(View.java:5609)
                                                         at android.view.View$PerformClick.run(View.java:22259)
                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                         at android.os.Looper.loop(Looper.java:154)
                                                         at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

`

**Comment by livotov** [comment]
I fixed that. The problem is you don't create subfolder ("pictures" or "videos", etc) in your PickerManager.getNewFileLocation method, so the file provider cannot find the final destination folder. Adding file.mkdirs(); solved the problem, just sent you a pull request with the fix.

**Comment by rt1909** [comment]
I still see the issue **android.os.FileUriExposedException** even when I updated the library to 1.1.2

**Comment by coomar2841** [comment]
Can you please post some logs?

**Comment by rtalari** [comment]
android.os.FileUriExposedException: file:///storage/emulated/0/Demo/DemoPictures/test.jpg exposed beyond app through Intent.getData()
                                                                         at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
                                                                         at android.net.Uri.checkFileUriExposed(Uri.java:2346)
                                                                         at android.content.Intent.prepareToLeaveProcess(Intent.java:8933)
                                                                         at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
                                                                         at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
                                                                         at android.app.Activity.startActivityForResult(Activity.java:4224)
                                                                         at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
                                                                         at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
                                                                         at android.app.Activity.startActivityForResult(Activity.java:4183)
                                                                         at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:871)
                                                                         at com.demo.fragments.ProfileFragment.onImagesChosen(ProfileFragment.java:357)
                                                                         at com.kbeanie.multipicker.core.threads.ImageProcessorThread$1.run(ImageProcessorThread.java:52)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by coomar2841** [comment]
Looks like some other issue. Can you post some code on what you are doing in ProfileFragment.onImagesChosen Line 357?

**Comment by rt1909** [comment]
if (image.getThumbnailPath() != null) {
            imagepath = image.getOriginalPath();
            Intent cropIntent = new Intent("com.android.camera.action.CROP");
            Uri uri = Uri.fromFile(new File(imagepath));
            mContext.grantUriPermission("com.android.camera", uri,
                    Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);
            cropIntent.setDataAndType(uri, "image/*");
            cropIntent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            cropIntent.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
            cropIntent.putExtra(MediaStore.EXTRA_OUTPUT, uri);
            ((Activity) mContext).startActivityForResult(getCropIntent(cropIntent), Utils.CROP_PIC);
        }

**Comment by coomar2841** [comment]
This is probably because you are using CROP_PIC after getting the image. Since you are correctly getting the image path already, looks like it's not the library's problem.
